version: '3.8'

services:
  pdfscrubber:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pdfscrubber
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - pdfscrubber-network

  # Development service
  pdfscrubber-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: pdfscrubber-dev
    volumes:
      - .:/app
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - ENVIRONMENT=development
      - BUILD_TYPE=Debug
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - pdfscrubber-network
    profiles:
      - development

  # Testing service
  pdfscrubber-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: pdfscrubber-test
    volumes:
      - .:/app
    working_dir: /app
    command: ./build.sh test
    networks:
      - pdfscrubber-network
    profiles:
      - testing

networks:
  pdfscrubber-network:
    driver: bridge
    name: pdfscrubber-network

volumes:
  pdfscrubber-data:
    driver: local
  pdfscrubber-config:
    driver: local